---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: update package
  become: true
  shell: sudo apt update

- name: install nodejs & npm
  become: true
  apt:
    name: ["nodejs"]
    state: latest

- name: install nodejs & npm
  become: true
  apt:
    name: ["npm"]
    state: latest

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
