---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: ~/project/.circleci/ansible/roles/deploy/files
    dest: ~/backend_app

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend_app
    npm i

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend_app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node
  args:
    chdir: ~/backend_app/dist
# - name: "move node modules"
#   become: yes
#   copy:
#     src: ~/project/backend/node_modules
#     dest: ./backend_app

# - name: Extract backend file
#   become: true
#   command: |
#     ls
#     cd ~/backend_app
#     tar -xvf artifact.tar.gz

# - name: deploay backend with ansible
#   become: true
#   command: |
#     ~/backend_app/artifact
#     npm install
#     pm2 stop default
#     pm2 start npm -- start
