---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: /root/project/backend/dist
    dest: ./backend_app
    recursive: true

- name: "move node modules"
  become: yes
  synchronize:
    src: /root/project/backend/node_modules
    dest: ./backend_app
    recursive: true
- name: "run server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: ./backend_app/dist
# - name: Extract backend file
#   become: true
#   command: |
#     ls
#     cd ~/backend_app
#     tar -xvf artifact.tar.gz

# - name: deploay backend with ansible
#   become: true
#   command: |
#     ~/backend_app/artifact
#     npm install
#     pm2 stop default
#     pm2 start npm -- start
