---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: ~/project/artifact.tar.gz
    dest: "~/backend_app/artifact.tar.gz"

- name: Extract backend file
  become: true
  command: |
    tar -xvf artifact.tar.gz

- name: deploay backend with ansible
  become: true
  command: |
    ~/backend_app/artifact
    npm install
    pm2 stop default
    pm2 start npm -- start
