---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: ~/project/.circleci/ansible/roles/deploy/files
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

# - name: "move node modules"
#   become: yes
#   copy:
#     src: ~/project/backend/node_modules
#     dest: ./backend_app
- name: "copy pachage.json"
  become: yes
  copy:
    src: ~/project/backend/package.json
    dest: ./backend_app

- name: "install npm package"
  become: true
  command: |
    ls
    cd ./backend_app
    npm install

- name: "run server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: ./backend_app/dist
# - name: Extract backend file
#   become: true
#   command: |
#     ls
#     cd ~/backend_app
#     tar -xvf artifact.tar.gz

# - name: deploay backend with ansible
#   become: true
#   command: |
#     ~/backend_app/artifact
#     npm install
#     pm2 stop default
#     pm2 start npm -- start
