# version of circle ci cloud
version: 2.1
#jobs have stesp of run command
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: build front end steps
          command: |
            ls
            cd frontend
            npm install
            npm run build
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: build front end steps
          command: |
            ls
            cd backend
            npm install
            npm run build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
